### ISSUE TITLE
codedefenders on Docker

### ISSUE THREAD

**Issue by AleMidolo** [CodeDefenders/CodeDefenders#12]
Hello, i'm trying to install codedefenders in my local VM with docker. I ran the build command with the dockerfile, and I have 4 different image but now I don't know what I have to do to start codedefender. Could you please tell me which steps I have to follow to properly configure docker ? Thank you.

**Comment by ein-stein-chen** [comment]
(I assume you have checked out the git tag `v1.8.1`.)

Since release 1.8 we publish ready-to-use [docker images on docker hub](https://hub.docker.com/r/codedefenders/codedefenders).

The `docker-compose.yml` uses these images and currently defaults to an old tag (`git-50f74405`).
So you need to overwrite this one with the tag you want to use.
Simply copy the `docker/.env.example` to `docker/.env` and uncomment the `CODEDEFENDERS_VERSION` environment variable.

You can either set this to one of the tags published on docker hub (e.g. leave it at `1.8.1`), or if you want to use your locally build image you would have to tag it (e.g.: `docker tag <imageId> codedefenders/codedefenders:local`) and then set the `CODEDEFENDERS_VERSION` environment variable to `dev`, either through the `.env` file or [any other way](https://docs.docker.com/compose/environment-variables/).

At this point, you should be able to run a `docker-compose up` from the `docker` directory and (after some seconds/minutes) get a running codedefenders instance listening on http://localhost:8080.

**Comment by AleMidolo** [comment]
Perfect, I followed your instructions and everything is working fine! I changed the Ip Address on the .yml file in order to access to codedefenders from external clients and not only from the localhost. Thank you very much for your help!
